ETCGrantsDAO/etc-grants-dao-website

src/locales/cn.json
src/locales/en.json
src/views/HomeView.vue

Also added shortened title for ETCin2023, for consistency, though the text is currently the same.

Updated mobile nav for About section

---

src/locales/cn.json
src/locales/en.json
src/views/HomeView.vue

Stripped out now unused Overview text strings.
Added clear comment marker between the two sections of text strings.

String cleanup.

---

src/views/HomeView.vue

Added grant categories text

---

src/views/HomeView.vue

We can add a new one if we make one.

Removed icon for now

---

src/components/Suggestions/index.vue
src/views/HomeView.vue

Suggestion -> Suggestions
Removed stray id in the wrong place.
Removed comments in HomeVue.js which are not needed anymore, because the file is so simple post-componentization

Minor cleanup

---

src/components/Process/index.vue
src/components/Requirements/index.vue

Copied from Scott's rejected PR

Fix links in main text

---

src/locales/cn.json

As of her Jan 14 json file.
I had to make some tiny tweaks.

Bring in all of Angelah's translations

---

src/components/Navbar/NavBar/index.vue

Some headings changes were lost, together with the airtable URL getting regressed.  Also, using fully qualified path for importing LocaleSwitcher.

Fixed regressions in the nav control

---

src/components/Resources/index.vue
src/locales/cn.json
src/locales/en.json

Just hyperlinks with headings.
Having to hardcode the URLs in the vue file because I cannot work out how to do the translation text for attributes.

Created content for resources page

---

src/assets/tailwind.css
src/components/Common/MainHeading/index.vue
src/components/Common/Paragraph/index.vue
src/components/Common/SubHeading/index.vue
src/components/Common/TH/index.vue
src/components/HowToApply/index.vue
src/components/Process/index.vue

Hi,
I have fixed the padding between headings and paragraph. 
I have changed the bullet points to css now. They are no more in html.
I have made the table view to 100% of section. Let me know if you need more work in it.

Fixed Padding, table view and bullet points

---

src/assets/tailwind.css
src/components/Resources/index.vue

And then using these bulletpoints on the Resources page, along with parrot green sub-headings

Using an actual bulletpoint

---

src/components/Overview/index.vue
src/views/HomeView.vue

The content changed a while back.

Rename About to Overview for Vue filename

---

src/locales/cn.json
src/locales/en.json

Brought d-oper changes into the Chinese text file, and corrected the broken nesting which broke the Chinese translations through the site.

Chinese fixes

---

src/components/HowToApply/index.vue
src/components/Resources/index.vue
src/locales/cn.json
src/locales/en.json

Switched to text for WeChat link.
Stripped out example link code for Chinese JSON.

Remove old table

---

src/components/Process/index.vue
src/locales/cn.json
src/locales/en.json

This regresses the Chinese translation of that paragraph which will need to be redone tomorrow.

Removed test links and did real links for the ETC Grants Program paragraph

---

src/components/Navbar/NavBar/index.vue

Not working and we don't have the space

Remove search button

---

src/md/etc-grants-process.en.md

Added more acceptable licenses, based on questions raised by the community.

Added more acceptable licenses

---

public/sitemap.xml

sitemap (#8)

---

src/md/overview.cn.md
src/md/overview.en.md

Updated URL for ETC multisig.
Previous one was invalidated by updated Safe deployment.

Fix multisig

---

src/components/Hero/index.vue
src/components/Navbar/NavBar/index.vue
src/locales/cn.json
src/locales/en.json

add Operation Report

---

src/md/overview.en.md

Updated the multisig address from broken link

Updated multisig address - CN overview.en.md
